services:
  backend:
    image: vue-portfolio-backend
    container_name: vue-portfolio-backend
    build:
      context: .
      target: backend
    environment:
      PORT: 5000
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    image: vue-portfolio-frontend
    container_name: vue-portfolio-frontend
    build:
      context: .
      target: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
